version: "3"

services:
  zookeeper:
    image: jplock/zookeeper:3.4.6

  kafka:
    image: ches/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
